version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-fpm-nginx
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/local-conf.d/:/usr/local/etc/php/local-conf.d/
    ports:
      - '8080:80'
    networks:
      sail:
        aliases:
          - localhost

  db:
    image: mysql:8.0.30
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: intensive
      MYSQL_USER: tuneyadec
      MYSQL_PASSWORD: tuneyadec
    volumes:
      - './drip_chip.sql:/docker-entrypoint-initdb.d/drip_chip.sql'
      - dbdata:/var/lib/mysql

    networks:
      sail:
        aliases:
          - localhost

#Docker Networks
networks:
  sail:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local